# eval/configs/baseline.yaml
# Baseline configuration - No TML dual-layer logging for comparison
name: baseline
backend: eval.backends.baseline:Runner
config:
  # Baseline has no TML dual-layer features
  enable_logging: false
  enable_dynamic_stream: false
  enable_static_anchor: false
  # No thresholds - framework-enforced in TML implementations
  
# Decoding parameters (for when using actual model)
decoding:
  temperature: 0.2
  top_p: 0.95
  max_tokens: 512

# Baseline metrics for comparison
metrics:
  track_latency: true
  track_decisions: true
  # No DS/SA tracking in baseline
  track_dynamic_stream: false
  track_static_anchors: false
  track_lite_traces: false

# Evidence-based accountability for AI systems
