# eval/configs/sacred_pause.yaml
# Configuration for Dual-Layer SPRL with Sacred Pause
name: sacred_pause
backend: eval.backends.sacred_pause:Runner
config:
  # Dual-layer architecture settings
  enable_dynamic_stream: true  # DS runs from t₀
  enable_static_anchor: true   # SA automatic at Sacred Pause
  
  # Framework-enforced (not configurable by deployer)
  # Thresholds are built into framework per SPRL spec
  # sprl_threshold: [REMOVED - framework enforced]
  
  # Logging configuration
  enable_logging: true
  enable_lite_traces: true     # Near-miss tracking
  retention_days: 1095          # 3 years minimum for full logs
  lite_trace_retention_days: 90 # Short retention for near-misses
  
  # Dual-layer specific
  ds_chunk_cadence_ms: 200     # Max interval per SPRL spec
  sa_atomic_write: true         # SA must be atomic
  sa_immutable: true           # SA cannot be modified
  
  # Non-blocking execution
  parallel_logging: true        # Always true in dual-layer
  max_latency_ms: 10           # Decision latency target
  
  # I × V × P formula components (for testing different scenarios)
  test_scenarios:
    low_risk:
      impact: 0.1
      vulnerability: 0.1
      probability: 0.1
    medium_risk:
      impact: 0.5
      vulnerability: 0.5
      probability: 0.5
    high_risk:
      impact: 0.9
      vulnerability: 0.9
      probability: 0.9

# Decoding parameters (for when using actual model)
decoding:
  temperature: 0.2
  top_p: 0.95
  max_tokens: 512

# Monitoring
monitoring:
  track_ds_continuity: true    # Verify DS runs from t₀
  track_sa_writes: true        # Monitor SA atomic writes
  track_invariants: true       # Check I1-I5 compliance
  track_spoliation: true       # Detect missing logs

# Evidence-based accountability for AI systems
