# eval/configs/sacred_pause.yaml
name: sacred_pause
backend: eval.backends.sacred_pause:Runner

config:
  low_conf_threshold: 0.80
  no_sleep: true  # true = skip time.sleep() for speed during eval, false = simulate pause

datasets:
  - eval/datasets/facts.jsonl
  - eval/datasets/ambiguous.jsonl
  - eval/datasets/harmful.jsonl
  - eval/datasets/creative.jsonl
